/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Base: typeof import('./components/Base.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    Handle1: typeof import('./components/picture_page/handle/Handle1.vue')['default']
    Handle2: typeof import('./components/picture_page/handle/Handle2.vue')['default']
    Handle3: typeof import('./components/picture_page/handle/Handle3.vue')['default']
    Handle4: typeof import('./components/picture_page/handle/Handle4.vue')['default']
    Handle5: typeof import('./components/picture_page/handle/Handle5.vue')['default']
    Handle6: typeof import('./components/picture_page/handle/Handle6.vue')['default']
    Handle7: typeof import('./components/picture_page/handle/Handle7.vue')['default']
    Handle8: typeof import('./components/picture_page/handle/Handle8.vue')['default']
    Handle9: typeof import('./components/picture_page/handle/Handle9.vue')['default']
    PicturePage: typeof import('./components/picture_page/PicturePage.vue')['default']
  }
}
